version: "3"
services:

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - "/root/minecraft:/data"
    restart: always

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /root/filebrowser:/data
    ports:
      - "8090:80"
    environment:
      - DATA_DIR=/
      - TZ=Asia/Shanghai  # 设置时区，根据需要调整
      - USERNAME=admin  # 设置登录用户名
      - PASSWORD=admin123  # 设置登录密码
    restart: always
    
  chatgpt-web:
    image: chatgptweb/chatgpt-web:latest
    container_name: chatgpt_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ACCESS_TOKEN=your_access_token  # 替换为您的 Access Token
      
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - /root/adguardhome/work:/opt/adguardhome/work
      - /root/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"

  alist:
    image: xhofe/alist-aria2
    container_name: alist
    restart: unless-stopped
    ports:
      - "5244:5244"
      - "6800:6800"
    environment:
      - PUID=0        
      - PGID=0      
    volumes:
      - /etc/alist:/opt/alist/data
      
  aapanel:
    image: aapanel/aapanel:lnmp
    container_name: aapanel
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/website_data:/www/wwwroot
      - /root/mysql_data:/www/server/data
      - /root/vhost:/www/server/panel/vhost

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /root/calibre-web/data:/config
      - /root/calibre-web/calibre/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  kodbox:
    image: kodcloud/kodbox
    container_name: kodbox
    ports:
      - 89:80
    volumes:
      - /root/kodbox:/var/www/html
    restart: unless-stopped

  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /root/qbittorrent/appdata:/config
      - /root/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - /root/ql/data:/ql/data

  tor-privoxy:
    image: dockage/tor-privoxy:latest
    container_name: tor-privoxy
    ports:
      - 9050:9050
      - 9051:9051
      - 8118:8118
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /root/vw-data:/data
    ports:
      - 86:80
    environment:
      - PUID=0        
      - PGID=0        
      - DATABASE_URL=postgresql://vaultwarden_user:your_password@postgres:5432/vaultwarden_db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=raspberrypi.local
      - PASSWORD=foobar123
      - WG_PORT=51820
    volumes:
      - /root/wireguard:/etc/wireguard
    ports:
      - 51822:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    ports:
      - "2342:2342"
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=photoprism
    volumes:
      - /root/photoprism:/photoprism
    restart: unless-stopped

  vocechat:
    image: privoce/vocechat-server:latest
    container_name: vocechat-server
    restart: unless-stopped
    ports:
      - '3019:3000'
    volumes:
      - '/root/vocechat:/home/vocechat-server/data' 
    
  xui:
    image: enwaiax/x-ui:alpha-zh
    container_name: xui
    volumes:
      - /root/xui/db/:/etc/x-ui/
      - /root/xui/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host    
    
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "8089:80"  
      
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    ports:
      - "8095:80"
    volumes:
      - /root/nextcloud:/home/wwwroot/nextcloud
    restart: unless-stopped
    
  synctv:
    image: 'synctvorg/synctv:latest'
    container_name: synctv
    restart: unless-stopped
    ports:
      - '8092:8080/tcp'
      - '8092:8080/udp'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_NAME=synctv
      
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning --requirepass yourpassword
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /root/redis:/data      
