version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /root/vw-data/:/data
    ports:
      - "86:80"

  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data

  mcserver:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - /root/mcserver:/data:rw
    ports:
      - "25565:25565"
    tty: true

  nginx:
    image: jc21/nginx-proxy-manager
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt

  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - "5700:5700"
    volumes:
      - /root/ql/data:/ql/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup

  aapanel:
    image: aapanel/aapanel:lnmp
    container_name: aapanel
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/website_data:/www/wwwroot
      - /root/mysql_data:/www/server/data
      - /root/vhost:/www/server/panel/vhost

  x-ui:
    image: enwaiax/x-ui:alpha-zh
    container_name: x-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/x-ui/db/:/etc/x-ui/
      - /root/x-ui/cert/:/root/cert/

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - /root/adguardhome/work:/opt/adguardhome/work
      - /root/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=raspberrypi.local
      - PASSWORD=foobar123
      - WG_PORT=51820
    volumes:
      - /root/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211
      - PLAYERS=16
      - SERVER_PASSWORD="worldofpals"
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - TZ="UTC"
      - ADMIN_PASSWORD="adminPasswordHere"
      - COMMUNITY=false
      - SERVER_NAME="palworld-server-docker by Thijs van Loef"
      - SERVER_DESCRIPTION="palworld-server-docker by Thijs van Loef"
    volumes:
      - /root/palworld:/palworld
