version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /root/vw-data/:/data
    ports:
      - "86:80"
  alist:
    image: xhofe/alist
    container_name: alist
    restart: always
    ports:
      - "5244:5244"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    volumes:
      - /etc/alist:/opt/alist/data
  mcserver:
    image: marctv/minecraft-papermc-server:latest
    container_name: mcserver
    restart: unless-stopped
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=
    volumes:
      - /root/mcserver:/data:rw
    ports:
      - "25565:25565"
    tty: true
  nginx:
    image: jc21/nginx-proxy-manager
     container_name: nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/data:/data
      - /root/letsencrypt:/etc/letsencrypt
  qinglong:
    image: whyour/qinglong
    container_name: qinglong
    hostname: qinglong
    restart: unless-stopped
    ports:
      - 5700:5700
    volumes:
      - /root/ql/data:/ql/data
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup
  aapanel:
    image: aapanel/aapanel:lnmp
    container_name: aapanel
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/website_data:/www/wwwroot
      - /root/mysql_data:/www/server/data
      - /root/vhost:/www/server/panel/vhost
  x-ui:
    image: enwaiax/x-ui:alpha-zh
    container_name: x-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - /root/x-ui/db/:/etc/x-ui/
      - /root/x-ui/cert/:/root/cert/
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - /root/adguardhome/work:/opt/adguardhome/work
      - /root/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"      
      
